### ISSUE TITLE
Precalculated values for different transcripts?

### ISSUE THREAD

**Issue by nbalanda23** [CshlSiepelLab/LINSIGHT#3]
I am trying to test LINSIGHT on HGMD and Clinvar datasets using variants in 5' and 3' UTRs. However, I am finding that some variants determined to be in these regions by HGMD do not have precomputed LINSIGHT scores. I found that at these positions, there is a minor variant transcript in which this position is part of a coding sequence and I am assuming that this is why LINSIGHT is not calculated for these positions. For example: HGMD dataset has variant at chr2:86444173 that is deemed non-coding (3'UTR) but there is no computed LINSIGHT score. What are the limits on the precomputed scores? How is non-coding being defined?

**Comment by huangyifeicmb** [comment]
A site is defined as noncoding if it does not overlap with any CDS region in GENCODE v19. Therefore, chr2:86444173 is considered as a part of coding sequence.

**Comment by vickneshrao95** [comment]
hi im new to this thing. I followed the manuals all but when i run the command 
"LINSIGHT-prep -i INSIGHT_database.ins -o binary_dir/"
the output is 
"LINSIGHT-prep: command not found"
i have tried to change the command to 
"L-INSIGHT-prep -i INSIGHT_database.ins -o binary_dir/" (since the file you posted is L-INSIGHT-prep.cpp" but 
the output is 
please help me, thanks.
